#include "commands_table.h"

const cmd_info cmd_table[CMD_COUNT] = {
	{"nop",   0, 0, {0}},
	{"hlt",   0, 0, {0}},

	{"int",   1, 1, {AT_BYTE, 0}},

	{"cpy",   2, 1, {AT_REG_REG, 0}},
	{"ldw",   2, 1, {AT_REG_REG, 0}},
	{"ldb",   2, 1, {AT_REG_REG, 0}},
	{"llb",   2, 1, {AT_REG_REG, 0}},
	{"lhb",   2, 1, {AT_REG_REG, 0}},
	{"ldwi",  2, 3, {AT_WORD, AT_REG, 0}},
	{"ldbi",  2, 3, {AT_WORD, AT_REG, 0}},
	{"llbi",  2, 3, {AT_WORD, AT_REG, 0}},
	{"lhbi",  2, 3, {AT_WORD, AT_REG, 0}},
	{"stw",   2, 1, {AT_REG_REG, 0}},
	{"slb",   2, 1, {AT_REG_REG, 0}},
	{"shb",   2, 1, {AT_REG_REG, 0}},
	{"stwi",  2, 3, {AT_REG, AT_WORD, 0}},
	{"slbi",  2, 3, {AT_REG, AT_WORD, 0}},
	{"shbi",  2, 3, {AT_REG, AT_WORD, 0}},
	{"ldi",   2, 3, {AT_WORD, AT_REG, 0}},
	{"lbi",   2, 3, {AT_WORD, AT_REG, 0}},
	{"lli",   2, 3, {AT_WORD, AT_REG, 0}},
	{"lhi",   2, 3, {AT_WORD, AT_REG, 0}},

	{"inc",   1, 1, {AT_REG, 0}},
	{"dec",   1, 1, {AT_REG, 0}},
	{"add",   2, 1, {AT_REG_REG, 0}},
	{"sub",   2, 1, {AT_REG_REG, 0}},
	{"mul",   2, 1, {AT_REG_REG, 0}},
	{"div",   2, 1, {AT_REG_REG, 0}},
	{"mod",   2, 1, {AT_REG_REG, 0}},
	{"shl",   2, 1, {AT_REG_REG, 0}},
	{"shr",   2, 1, {AT_REG_REG, 0}},
	{"or",    2, 1, {AT_REG_REG, 0}}, 
	{"and",   2, 1, {AT_REG_REG, 0}},
	{"xor",   2, 1, {AT_REG_REG, 0}},
	{"not",   1, 1, {AT_REG, 0}},

	{"jeq",   3, 3, {AT_REG_REG, AT_WORD, 0}},
	{"jne",   3, 3, {AT_REG_REG, AT_WORD, 0}},
	{"jlt",   3, 3, {AT_REG_REG, AT_WORD, 0}},
	{"jgt",   3, 3, {AT_REG_REG, AT_WORD, 0}},
	{"jle",   3, 3, {AT_REG_REG, AT_WORD, 0}},
	{"jge",   3, 3, {AT_REG_REG, AT_WORD, 0}},
	{"jmp",   1, 2, {AT_WORD, 0}},
	{"jpr",   1, 1, {AT_REG, 0}},

	{"callr", 1, 1, {AT_REG, 0}},
	{"callv", 1, 2, {AT_WORD, 0}},
	{"pushr", 1, 1, {AT_REG, 0}},
	{"pushv", 1, 2, {AT_WORD, 0}},
	{"pop",   1, 1, {AT_REG, 0}},
	{"ret",   0, 0, {0}},

	{"in",    2, 2, {AT_BYTE, AT_REG, 0}}, 
	{"out",   2, 2, {AT_REG, AT_BYTE, 0}} 
};
